UI (Selenium and BDD) tests
gibbonsite/Diploma_AQA18_onl pull request #1
Opened 2023-02-26 14:04 UTC by gibbonsite

UI (Selenium and BDD) tests are ready to be checked and merged into develop branch.

2023-03-04 14:55 UTC, wildpioneer requested changes

2023-03-04 14:55 UTC, wildpioneer commented on src/test/java/baseentities/BasePage.java
> +    protected WebDriver driver;
архитектурно не совсем верно.

В BaseCucumberTest  тебя драйвер статичный - а значит два момента:
1. Он всегда будет в единственном варианте
2. К нему можно обратиться из любого места

в следствии этого не совсем понятно зачем делать в BasePage драйвер? 
У меня вообще возникает желание объединить два этих класса в один

2023-03-04 14:55 UTC, wildpioneer commented on src/test/java/RunSmokeCucumberTest.java
> +        tags = "@SmokeTest"
Все три файла отличаются только использованием различного @tag. Однако существует возможность запускать тесты с определенным @tag из командной строки. 
Следовательно - в рамках дипломной работы зачту, но в жизни мы так не используем

2023-03-04 14:55 UTC, wildpioneer commented on src/test/java/pages/DashboardPage.java
> +    public static class EditUserStatusDialogWindow extends BasePage {
1. Почему static?
2. Почему внутри этого класса?

2023-03-04 14:55 UTC, wildpioneer commented on src/test/java/pages/repository/RepositoryPage.java
> +            "[id='repository-container-header'] strong > a");
для ID в CSS существует сокращенная запись

2023-03-04 14:55 UTC, wildpioneer commented on src/test/java/pages/repository/RepositorySettingsPage.java
> +                "//*[contains(text(), 'Unexpected bad things')]/following-sibling::*[1]//input[@type='text']");
Без индекса никак?

2023-03-04 14:55 UTC, wildpioneer commented on src/test/java/stepdefs/Hook.java
> +    public void initScenario(Scenario scenario) {
А почем hook в definition папке?

2023-03-04 14:55 UTC, wildpioneer commented on src/test/resources/features/repository.feature
> +      | DiplomaAqa18Onl | RepositoryDeletion01 |
А тут так и будет только один ряд значений? В таком случае таблица здесь не будет иметь смысла

2023-03-08 19:53 UTC, gibbonsite commented on src/test/java/baseentities/BasePage.java
> +    protected WebDriver driver;
Исправлено.

2023-03-08 19:56 UTC, gibbonsite commented on src/test/java/RunSmokeCucumberTest.java
> +        tags = "@SmokeTest"
По заданию нужно сделать в testng.xml разные наборы для smoke и regression-тестирования. В testng.xml прописываются классы с тестами в теге <classes>. По этой причине созданы разные классы.

2023-03-08 19:57 UTC, gibbonsite commented on src/test/java/pages/DashboardPage.java
> +    public static class EditUserStatusDialogWindow extends BasePage {
Исправлено.

2023-03-08 19:57 UTC, gibbonsite commented on src/test/java/pages/repository/RepositoryPage.java
> +            "[id='repository-container-header'] strong > a");
Исправлено.

2023-03-08 19:57 UTC, gibbonsite commented on src/test/java/pages/repository/RepositorySettingsPage.java
> +                "//*[contains(text(), 'Unexpected bad things')]/following-sibling::*[1]//input[@type='text']");
Исправлено.

2023-03-08 19:57 UTC, gibbonsite commented on src/test/java/stepdefs/Hook.java
> +    public void initScenario(Scenario scenario) {
Исправлено.

2023-03-08 19:58 UTC, gibbonsite commented on src/test/resources/features/repository.feature
> +      | DiplomaAqa18Onl | RepositoryDeletion01 |
Обсудили на занятии, что можно не трогать таблицу.

2023-03-08 20:00 UTC, merged